# Site settings
title: Andreas Flodström | Portfolio
description: Game Dev Portfolio
url: "https://andreasflodstrom.github.io"
baseurl: "" 


markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag


author:
  name: Andreas Flodström
  email: andreas.flodan@hotmail.com


social_links:
  github: https://github.com/AndreasFlodstrom
  linkedin: https://www.linkedin.com/in/andreas-flodstr%C3%B6m-a22805236/
